version: '3.8'

services:
  mongodb:
    image: mongo:6  # Local image
    container_name: my_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - internal_network

  nextjs:
    build: .
    container_name: my_nextjs
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://root:example@mongodb:27017"
    networks:
      - internal_network

volumes:
  mongo_data:

networks:
  internal_network:
    driver: bridge
