services:
  mongodb:
    image: mongo:6
    container_name: wordalex_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  nextjs:
    build:
      context: ./
      args:
        - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
        - MONGODB_DB_NAME=${MONGODB_DB_NAME}
        - MONGODB_COLLECTION_NAME=${MONGODB_COLLECTION_NAME}
        - LDAP_URL=${LDAP_URL}
        - JWT_SECRET=${JWT_SECRET}
        - SYM_ENC_KEY=${SYM_ENC_KEY}
      dockerfile: Dockerfile
    container_name: wordalex_nextjs
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - MONGODB_COLLECTION_NAME=${MONGODB_COLLECTION_NAME}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - LDAP_URL=${LDAP_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SYM_ENC_KEY=${SYM_ENC_KEY}
    env_file:
      - ./.env
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: wordalex_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "27443:27443"
    volumes:
      - ./Certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mongodb
      - nextjs
    networks:
      - frontend
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
